### ISSUE TITLE
synsanity vs iptables-synproxy

### ISSUE THREAD

**Issue by dimsua** [github/synsanity#1]
Hello
synsanity faster then iptables synproxy in el7(http://rhelblog.redhat.com/2014/04/11/mitigate-tcp-syn-flood-attacks-with-red-hat-enterprise-linux-7-beta/)?
Did you testing synsanity vs iptables synproxy?

**Comment by theojulienne** [comment]
> Did you testing synsanity vs iptables synproxy?

We discussed this a bit in the [launch blog post](http://githubengineering.com/syn-flood-mitigation-with-synsanity/): synsanity is using the same technique (and some of the same source code) as synproxy, except that it must be run on the end host (not an intermediary firewall). The primary difference is that synsanity doesn't touch packets once connections are established.

**Comment by minhdanh** [comment]
@theojulienne From this image in the launch blog post: ![](http://githubengineering.com/images/syn-flood-mitigation-with-synsanity/synsanity.png) 
I can see that sansinity doesn't send a SYN packet and receive a SYN-ACK one to the TCP stack. How can a connection could be established between the client and the server's TCP stack in this case?

**Comment by theojulienne** [comment]
@minhdanh synsanity matches the way the Linux kernel sends and signs syncookies, so it never needs to send a SYN to the TCP stack. Instead, when the ACK arrives and the syncookie is validated, the ACK itself is passed directly on to the kernel and the kernel assumes it sent the syncookie (since it looks the same as if it did), so creates the connection state.
